version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    expose:
      - '29092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - kafka-net


  init-kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - broker
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      kafka-topics --bootstrap-server broker:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic events.taxonomy --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic bets.state --replication-factor 1 --partitions 3
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server broker:29092 --list
      "
    networks:
      - kafka-net

  db:
    image:  postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
    depends_on:
      - init-kafka
    networks:
      - kafka-net

  dbui:
    image: dpage/pgadmin4:6
    ports:
      - "8080:8080"
    environment:
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_DEFAULT_EMAIL: ia01.irina.telesnenko@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    networks:
      - kafka-net


  bets:
    build: ./bets
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - init-kafka
    networks:
      - kafka-net


  events:
    build: ./events
    ports:
      - "8001:81"
    restart: always
    depends_on:
      - bets
    networks:
      - kafka-net

  event_writer:
    build: ./event_writer
    ports:
      - "8002:82"
    restart: always
    depends_on:
      - events
    networks:
      - kafka-net

  bet_scorer:
    build: ./bet_scorer
    ports:
      - "8003:83"
    restart: always
    depends_on:
      - event_writer
    networks:
      - kafka-net

  bet_writer:
    build: ./bet_writer
    ports:
      - "8004:84"
    restart: always
    depends_on:
      - bet_scorer
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge